name: GPT-4 PR Review
description: A PR Review Bot Powered By OpenAI GPT-4

inputs:
  repository:
    description: "The target repository"
    required: true
  github_token:
    description: "GitHub Token"
    required: true
  GPT_4_API_KEY:
    description: "Your GPT-4 API key"
    required: true
  sha:
    description: "Github SHA"
    required: true
  pat:
    description: "Github PAT"
    required: true
  pull_request:
    description: "Github pull_request"
    required: true

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pr_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.sha }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install PyGithub openai

      - name: Run GPT-4 PR Review
        id: pr_review
        env:
          GPT_4_API_KEY: ${{ inputs.GPT_4_API_KEY }}
        run: |
          python .github/actions/gpt4_pr_review.py ${{ inputs.pat }} ${{ inputs.repository }} ${{ inputs.pull_request }}

      - name: Add PR review comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ inputs.github_token }}
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('gpt4_output.txt', 'utf8');
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'COMMENT',
              body: output
            });
